name: Publish blog

on:
  push:
    branches: [ main ]
  issues:
    types: [labeled]

jobs:
  publish:
    name: Generate page
    runs-on: ubuntu-latest
    if: github.event.label.name == 'publish'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: AddLink
        run: |
          git config --global user.name "MengqingCao"
          git config --global user.email "cmq0113@163.com"
          python addBlog.py ./knowledge/hexo/cosdt.github.io-hexo/knowledgeMap/index.html github.event.issue.title github.event.issue.number github.event.label.name
          git commit -m "Update HTML with Issue #$github.event.issue.number"
          git push origin $GITHUB_REF
